test_that("unloading leaves no trace", {
  library(mlr3proba)
  library(mlr3pipelines)
  n_learners = length(mlr_learners$keys(pattern = "surv"))
  n_measures = length(mlr_measures$keys(pattern = "surv|dens"))
  n_tasks = length(mlr_tasks$keys())
  n_task_gens = length(mlr_task_generators$keys())
  n_pipeops = length(mlr_pipeops$keys())
  n_graphs = length(mlr_graphs$keys())
  expect_true(n_learners > 0)
  expect_true(n_measures > 0)
  expect_true(n_tasks > 0)
  expect_true(n_task_gens > 0)
  expect_true(n_pipeops > 0)
  expect_true(n_graphs > 0)

  unloadNamespace("mlr3proba")
  n_learners = length(mlr_learners$keys(pattern = "surv"))
  n_measures = length(mlr_measures$keys(pattern = "surv"))
  n_tasks_mlr3 = length(mlr_tasks$keys())
  n_task_gens_mlr3 = length(mlr_task_generators$keys())
  n_pipeops_mlr3 = length(mlr_pipeops$keys())
  n_graphs_mlr3 = length(mlr_graphs$keys())
  expect_equal(n_learners, 0)
  expect_equal(n_measures, 0)
  expect_true(n_tasks_mlr3 < n_tasks)
  expect_true(n_task_gens_mlr3 < n_task_gens)
  expect_true(n_pipeops_mlr3 < n_pipeops)
  expect_true(n_graphs_mlr3 < n_graphs)
})
