test_that("unloading leaves no trace", {
  library(mlr3proba)
  library(mlr3pipelines)
  n_learners = length(mlr_learners$keys(pattern = "surv"))
  n_measures = length(mlr_measures$keys(pattern = "surv|dens"))
  n_tasks = length(mlr_tasks$keys())
  n_task_gens = length(mlr_task_generators$keys())
  n_pipeops = length(mlr_pipeops$keys())
  n_graphs = length(mlr_graphs$keys())
  expect_gt(n_learners, 0L)
  expect_gt(n_measures, 0L)
  expect_gt(n_tasks, 0L)
  expect_gt(n_task_gens, 0L)
  expect_gt(n_pipeops, 0L)
  expect_gt(n_graphs, 0L)

  unloadNamespace("mlr3proba")
  n_learners = length(mlr_learners$keys(pattern = "surv"))
  n_measures = length(mlr_measures$keys(pattern = "surv"))
  n_tasks_mlr3 = length(mlr_tasks$keys())
  n_task_gens_mlr3 = length(mlr_task_generators$keys())
  n_pipeops_mlr3 = length(mlr_pipeops$keys())
  n_graphs_mlr3 = length(mlr_graphs$keys())
  expect_identical(n_learners, 0L)
  expect_identical(n_measures, 0L)
  expect_lt(n_tasks_mlr3, n_tasks)
  expect_lt(n_task_gens_mlr3, n_task_gens)
  expect_lt(n_pipeops_mlr3, n_pipeops)
  expect_lt(n_graphs_mlr3, n_graphs)
})
