#' @title PipeOpPredClassifSurvIPCW
#' @name mlr_pipeops_trafopred_classifsurv_IPCW
#'
#' @description
#' Transform [PredictionClassif] to [PredictionSurv].
#'
#' @section Dictionary:
#' This [PipeOp][mlr3pipelines::PipeOp] can be instantiated via the
#' [dictionary][mlr3misc::Dictionary] [mlr3pipelines::mlr_pipeops]
#' or with the associated sugar function [mlr3pipelines::po()]:
#' ```
#' PipeOpPredClassifSurvIPCW$new()
#' mlr_pipeops$get("trafopred_classifsurv_IPCW")
#' po("trafopred_classifsurv_IPCW")
#' ```
#'
#' @section Input and Output Channels:
#' The input is a [PredictionClassif] and a vector containing observed times
#' both generated by [PipeOpTaskSurvClassifIPCW].
#' The output is the input [PredictionClassif] transformed to a [PredictionSurv].
#' Only works during prediction phase.
#'
#' @family PipeOps
#' @family Transformation PipeOps
#' @export
PipeOpPredClassifSurvIPCW = R6Class(
  "PipeOpPredClassifSurvIPCW",
  inherit = mlr3pipelines::PipeOp,

  public = list(
    #' @description
    #' Creates a new instance of this [R6][R6::R6Class] class.
    #' @param id (character(1))\cr
    #' Identifier of the resulting object.
    initialize = function(id = "trafopred_classifsurv_IPCW") {
      super$initialize(
        id = id,
        input = data.table(
          name = c("input", "data"),
          train = c("NULL", "*"),
          predict = c("PredictionClassif", "*")
        ),
        output = data.table(
          name = "output",
          train = "NULL",
          predict = "PredictionSurv"
        )
      )
    }
  ),

  private = list(
    .predict = function(input) {
      pred = input[[1]]
      times = input[[2]]

      p = PredictionSurv$new(row_ids = pred$row_ids,
                             truth = Surv(time = times,
                                          event = as.integer(pred$truth)),
                             crank = pred$prob[, 2])
      list(p)
    },

    .train = function(input) {
      self$state = list()
      list(input)
    }
  )
)

register_pipeop("trafopred_classifsurv_IPCW", PipeOpPredClassifSurvIPCW)
