# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_assert_surv <- function(mat) {
    .Call(`_mlr3proba_c_assert_surv`, mat)
}

c_score_logloss <- function(obs_times, times, cdf, eps) {
    .Call(`_mlr3proba_c_score_logloss`, obs_times, times, cdf, eps)
}

c_score_graf_schmid <- function(obs_times, times, cdf, power = 2L) {
    .Call(`_mlr3proba_c_score_graf_schmid`, obs_times, times, cdf, power)
}

c_apply_ipcw_weights <- function(score, unique_times, truth, cens, eps) {
    .Call(`_mlr3proba_c_apply_ipcw_weights`, score, unique_times, truth, cens, eps)
}

c_concordance <- function(time, status, crank, t_max, weight_meth, cens, surv, tiex) {
    .Call(`_mlr3proba_c_concordance`, time, status, crank, t_max, weight_meth, cens, surv, tiex)
}

c_gonen <- function(crank, tiex) {
    .Call(`_mlr3proba_c_gonen`, crank, tiex)
}

